### ISSUE TITLE
Not able to get screen while executing the script in jenkins (Headless mode)

### ISSUE THREAD

**Issue by ajitkes** [getgauge/taiko#999] opened 2020-01-06 14:39 UTC
### Expected behavior
Screenshots should get displayed in html report (jenkins execution)

### Actual behavior
Not able to get screenshots

### Steps to reproduce
1.  gauge.screenshot({fullPage:true});
2.  Set headless_chrome = true
3. not getting screenshots in html report

Note: able to get screenshots when headless_chrome = false

### Versions
```
taiko 1.0.3
```

**Comment by zabil** [comment] 2020-01-06 15:12
Have you overriden the custom screenshot as follows?

```
// Using Taiko
// Return a screenshot byte array
gauge.screenshotFn = async function() {
    return await screenshot({ encoding: 'base64' });
};
```

For more details please refer https://docs.gauge.org/writing-specifications.html?os=windows&language=javascript&ide=vscode#taking-custom-screenshots

And conversation on spectrum

https://spectrum.chat/taiko/general/while-executing-the-script-in-jenkins-headless-mode-not-able-to-capture-screenshot~6a480b1e-083b-4a5d-9eae-7489bbde4224?m=MTU3ODMwNTIwNDUxOA==

**Comment by negiDharmendra** [comment] 2020-01-16 10:16
@ajitkes Any updates on this.

**Comment by ajitkes** [comment] 2020-01-17 09:10
@negiDharmendra  i am still facing the same issue..Not able to capture screenshot in index.html report (jenkins headless mode)

**Comment by sriv** [comment] 2020-02-12 05:47
@ajitkes - from [your post ](https://spectrum.chat/taiko/general/while-executing-the-script-in-jenkins-headless-mode-not-able-to-capture-screenshot~6a480b1e-083b-4a5d-9eae-7489bbde4224?m=MTU3ODMyNDM4MzgyMA==) it seems that the issue is probably related to your environment.

I am closing this, since do not have any way of replicating the issue. Please feel free to comment if you find something that can give us a hint.

**Closed by sriv** 2020-02-12 05:47 UTC
