### ISSUE TITLE
screenshot doesn work

### ISSUE THREAD

**Issue by zhangty0101** [getgauge/taiko#1350] opened 2020-07-12 15:20 UTC
screenshot({fullPage: true}) get white page out of screen view

**Comment by BugDiver** [comment] 2020-07-13 06:16
@zhangty0101 Thanks for reporting. I could replicate this. We will work on it soon.

**Comment by saikrishna321** [comment] 2020-07-14 05:48
This is a upstream issue - https://github.com/getgauge/taiko/issues/346

**Comment by zabil** [comment] 2020-07-20 12:21
Closing as duplicate of #346 and the fix needs be done in Chromium.

**Closed by zabil** 2020-07-20 12:21 UTC
