### ISSUE TITLE
How to intercept the API when mulltiple instance of API exist in the same name

### ISSUE THREAD

**Issue by jeevankumar22** [getgauge/taiko#2248] opened 2021-08-11 09:21 UTC
End point : https://example.com/questions/config
API 	  : config

Scenario : 

When i navigate to my application two API call exist in the same ( config ) , i.e two instance of API with same name

the difference between this two API call is payload 

Below is the sample payload of these two instance of API 

API call 1 : 
Payload : 
types: ["modal", "tab", "mobile number", "name", "cost"]

API call 2 : 
Payload : ["name", "address"]

Challenge : 
When i try to intercept from the tool, its always intercepting the first API call / instance
How do we instruct the taiko to mock the second instance of API / how to instruct taiko to check the header for all the instance of API and intercept the API based on the certain condition

I followed the available methods from the documentation , but couldn't solve this problem , taiko looking API with name , once matching instance is found its trying to intercept, but in my case i want to iterate all the instance of API call and based on the condition it should intercept

**Comment by zabil** [comment] 2021-08-11 09:26
Duplicate of https://docs.gauge.org/configuration.html?os=macos&language=javascript&ide=vscode#language-plugin-configurations

**Closed by zabil** 2021-08-11 09:26 UTC
