### ISSUE TITLE
Unable to automate the alert popup

### ISSUE THREAD

**Issue by tariquesalat386** [getgauge/taiko#962] opened 2019-12-10 05:20 UTC
![alert error](https://user-images.githubusercontent.com/58719426/70498029-1d7d6900-1b3b-11ea-94a3-adc502b2bfbf.JPG)

### Expected behavior
OK or Cancel button in the alert popup should be clicked automatically in taiko-gauge.

### Actual behavior
Unable to click or automate

### Steps to reproduce
This is limited to company standards so cannot mention the steps to reproduce.

### Versions
Paste `node` and `taiko` versions here.
node - 12.7.0
taiko - 0.0.1

**Comment by nehashri** [comment] 2019-12-11 06:47
@tariquesalat386 It looks like you need to override some permissions to on your url.
Please look at https://taiko-preview.gauge.org/#overridepermissions to override them.

**Comment by tariquesalat386** [comment] 2019-12-11 08:28
> @tariquesalat386 It looks like you need to override some permissions to on your url.
> Please look at https://taiko-preview.gauge.org/#overridepermissions to override them.

**Comment by tariquesalat386** [comment] 2019-12-11 08:29
@nehashri yes I tried by overriding permission as 

await overridePermissions('site-name'); but still it isn't working

**Comment by tariquesalat386** [comment] 2019-12-11 08:48
@nehashri yes I tried by overriding permission as

await overridePermissions('site-name'); but still it isn't working

**Comment by shubhamsc** [comment] 2019-12-16 10:05
@tariquesalat386  you need to set override Permissions with a type ex-
`await overridePermissions('<url>',['geolocation']);`

Please look at this conversation, which may help you to resolve the issue.
https://spectrum.chat/taiko/general/hi-all-is-there-a-way-to-click-alert-style-pop-up-box-using-taiko~7bdb9977-a409-4d86-9e89-03768a252329

**Comment by shubhamsc** [comment] 2019-12-20 08:48
Closing this issue as you start a new thread in https://spectrum.chat/taiko/general/unable-to-automate-alert-popup-in-taiko~fe99fa46-d6f7-4837-b418-ef770f87fb6b. Let us know the issue is resolved or you're still facing the issue with the alert popup.

**Closed by shubhamsc** 2019-12-20 08:48 UTC

**Comment by RedEyePilot** [comment] 2023-04-04 02:18
I wish so much the entire discussion would have been kept in the same space. Now spectrum.chat is disabled, gitter.im is non existent and instead of keeping documentation in one reliable place it is lost forever and I will have to open a new issue ticket for the same thing without having a chance to try what was already tried and could have worked
