### ISSUE TITLE
I am getting this error while running tests locally in my system  Error: Chromium revision is not downloaded. Provide TAIKO BROWSER PATH or Install taiko again to download bundled chromium

### ISSUE THREAD

**Issue by shaifaliyadav** [getgauge/taiko#2300] opened 2021-09-06 11:11 UTC

**Comment by zabil** [comment] 2021-09-06 20:32
Closing and duplicate of https://github.com/getgauge/taiko/issues/2235 please carry on the discussion there. Can you please add more info on the environment where you are trying to run Taiko? It will be much easier to find help if you fill up the issue template with more information on the original issue.

**Closed by zabil** 2021-09-06 20:32 UTC
