### ISSUE TITLE
Not able to run taiko using firefox on windows .Please kindly suggest

### ISSUE THREAD

**Issue by karishmayadava23** [getgauge/taiko#2696] opened 2023-04-11 07:03 UTC
### Discussed in https://github.com/getgauge/taiko/discussions/2694

<div type='discussions-op-text'>

<sup>Originally posted by **karishmayadava23** April 10, 2023</sup>
Hi ,

Tried running taiko on firefox/windows11. But unable to run followed below steps -
1. Installed firefox nightly from https://www.mozilla.org/en-US/firefox/all/#product-desktop-nightly
2.  on vscode terminal wrote below code to run the taiko in repl mode
TAIKO_BROWSER_PATH= C:\\Program Files\\Firefox Nightly\\firefox.exe  npx taiko 
but getting below error as it is not recognizing the executable path of firefox executable file.
Please suggest as providing the correct path
![image](https://user-images.githubusercontent.com/59534066/230838949-c8db117b-6793-40c5-8f26-29346fd19776.png)
</div>

**Comment by zabil** [comment] 2023-04-11 08:14
Duplicate of https://github.com/getgauge/taiko/discussions/2694

**Closed by zabil** 2023-04-11 08:14 UTC
