### ISSUE TITLE
taiko failures should include user code location in stacktrace

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#817] opened 2019-09-17 05:52 UTC
### Expected behavior
Taiko's failure stacktrace should include location of the user code.

### Actual behavior
The top element of the stacktrace point's to taiko's code implementation and does not point to the user code.

### Steps to reproduce
1. Save the below file as `example.js`

```
const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://gauge.org');
    await click('Get startedd');
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

2. Run `taiko example.js`
3. Notice the stacktrace.

### Versions
```
> taiko --version
Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE

> node --version
v10.16.0
 
```

**Comment by nehashri** [comment] 2019-09-17 12:32
This seems to be an issue with node versions less than 12. Node 12 introduced handling error stacktraces in async code. With versions greater that 12, you should see the complete stack trace.

**Comment by spinningarrow** [comment] 2019-09-24 11:03
Thanks for looking into this. Here are my platform details:

OS: macOS 10.14.6
Node: v12.10.0
npm: 6.11.3

Output:

![image](https://user-images.githubusercontent.com/1797328/65506298-8dc90680-decb-11e9-8770-a1eefd004c80.png)

Unfortunately I don't have a sample project that reproduces the issue yet, as the code is in a private repository. I'll try to whip something up when time permits.

**Comment by BugDiver** [comment] 2019-09-25 08:28
@spinningarrow I tried to replicate this issue with following setups

* In a docker container with nodejs 12.10.0 -> I could see the actual stack trace with user code
* A sample script (given ☝️) with taiko runner and nodejs 12.10.0 -> I could see the actual stack trace with user code
* A sample test case with jest, taiko and nodejs 12.10.0 -> I could see the actual stack trace with user code

Can you make sure that your tests are using the nodejs version 12.10.0 (If you are using nvm and have multiple version of nodejs installed)?
Maybe include a console.log for nodejs version in your test code.

Example: 
```
test('should ', async () => {
        await goto('https://gauge.org');
        console.log(process.version);
        await click('Get startedd');
    })
```

**Comment by spinningarrow** [comment] 2019-09-25 09:29
Node.js version from a console.log in the test:

```javascript
 console.log functional_tests/user_journey/create-and-manage-user.taiko.spec.js:18
    v12.10.0
```

**Comment by spinningarrow** [comment] 2019-09-25 09:41
Here's the test I'm using:

```javascript
import { $, click, closeBrowser, goto, into, openBrowser, write } from 'taiko'

describe('[TAIKO] Show stacktraces on failure', () => {
	jest.setTimeout(60000)

	afterAll(async () => {
		await closeBrowser()
	})

	test('failing test', async () => {
		await openBrowser()
		await goto('https://gauge.org')
		await click('Get startedd')
	})
})
```

Here's the output when it fails:

```
> jest --config functional_tests/jest.config.user_journey.js -w 1

 FAIL  functional_tests/user_journey/create-and-manage-user.taiko.spec.js (12.619s)
  [TAIKO] Show stacktraces on failure
    ✕ failing test (11598ms)

  ● [TAIKO] Show stacktraces on failure › failing test

    Element with text Get startedd not found

      at elements (../node_modules/taiko/lib/taiko.js:2701:15)
      at _click (../node_modules/taiko/lib/taiko.js:801:89)
      at click (../node_modules/taiko/lib/taiko.js:861:9)
      at Object.<anonymous>.module.exports.<computed> (../node_modules/taiko/lib/taiko.js:2899:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        12.978s, estimated 13s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test:user_journey: `jest --config functional_tests/jest.config.user_journey.js -w 1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test:user_journey script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sabajaj/.npm/_logs/2019-09-25T09_40_29_925Z-debug.log
Aborting due to errexit on line 402. Exit code: 1
```

**Comment by BugDiver** [comment] 2019-09-25 10:16
That is weird. The same test gives me the stack trace. here is my out put
```
> jest

 FAIL  ./foo.test.js (16.242s)
  [TAIKO] Show stacktraces on failure
    ✕ failing test (15421ms)

  ● [TAIKO] Show stacktraces on failure › failing test

    Element with text Get startedd not found

      11 | 		await openBrowser()
      12 | 		await goto('https://gauge.org')
    > 13 | 		await click('Get startedd')
         | 		^
      14 | 	})
      15 | })

      at elements (node_modules/taiko/lib/taiko.js:2701:15)
      at _click (node_modules/taiko/lib/taiko.js:801:89)
      at click (node_modules/taiko/lib/taiko.js:861:9)
      at Object.<anonymous>.module.exports.<computed> (node_modules/taiko/lib/taiko.js:2899:20)
      at Object.<anonymous> (foo.test.js:13:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        16.892s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Notice the last line of the stack trace is from the test code.

The only difference here is that i'm not using `babel` or something with `jest` so I have to change the import statements from
`import { $, click, closeBrowser, goto, into, openBrowser, write } from 'taiko'`
to
`const { click, closeBrowser, goto, openBrowser }  = require('taiko');`

**Comment by nehashri** [comment] 2019-09-25 10:42
@spinningarrow I see that you are using jest with some configuration (use of `--config` flag). Can you please let us know what configurations has been setup, it may help us debug further.

**Comment by spinningarrow** [comment] 2019-09-25 10:54
@BugDiver Hmm, I think it's quite possible that the babel stuff is interfering with the stacktraces somehow.

@nehashri yup, I finally got a repo for you to look at: https://github.com/spinningarrow/taiko-stack-trace

**Comment by BugDiver** [comment] 2019-09-25 11:04
@spinningarrow  With the repo which you shared, I am able to replicate your issue. It's something to do with `babel`.

**Comment by spinningarrow** [comment] 2019-09-25 11:04
Great. At least it's consistent!

I pushed a change to remove some unused stuff. I also added another test (not using taiko) that does show a stacktrace.

**Comment by BugDiver** [comment] 2019-09-25 11:20
@spinningarrow I made some changes in the `babel` config and turns out I was able to get the actual stacktrace. Here is what I did
* Install `babel-preset-latest-node` preset
* Add it to `babel` presets
```js
const presets = [["latest-node", { "target": "current" }], "@babel/preset-react"];
```
After making these changes when I ran the tests I got the actual stack trace.

```

      at elements (../node_modules/taiko/lib/taiko.js:2701:15)
      at _click (../node_modules/taiko/lib/taiko.js:801:89)
      at click (../node_modules/taiko/lib/taiko.js:861:9)
      at Object.<anonymous>.module.exports.<computed> (../node_modules/taiko/lib/taiko.js:2899:20)
      at Object.<anonymous> (user_journey/taiko.spec.js:13:3)
```

Notice the last line.

**Comment by spinningarrow** [comment] 2019-09-25 12:32
Cool, I'll try that and get back to you. Any idea why this problem only happens with taiko?

**Comment by spinningarrow** [comment] 2019-09-25 12:46
Hmm, doesn't seem to be working either. I might've done something silly though! I've pushed the change to the repo.

**Comment by BugDiver** [comment] 2019-09-26 06:25
@spinningarrow I tried with the latest changes in your repo. And you are right I don't see the stack trace but when I removed the following lines from `.babelrc` It worked.
```
[
      "@babel/preset-env",
      {
        "targets": {
          "chrome": "58",
          "ie": "11"
        }
      }
    ]
```

The reason is if this preset is available babel will transpile the code for `chrome 58` or `ie 11`, and my guess is that version does not support async stack traces.
So if you add only one preset for the current node. It works.

Could you please give it a try?

**Comment by spinningarrow** [comment] 2019-10-01 07:56
I'll give it a try. However, we need the preset for Chrome and IE because those are the browser targets for the non-test code.

**Comment by spinningarrow** [comment] 2019-10-01 08:03
Cool. The latest change works. I used the instructions from the Jest docs on ["Making your Babel config jest-aware"](Making your Babel config jest-aware).

Thanks for your help!

**Comment by Apoorva-GA** [comment] 2019-10-01 10:56
Great that it works now. Closing the issue.

**Closed by Apoorva-GA** 2019-10-01 10:56 UTC
Labels: bug
