### ISSUE TITLE
Taiko should fail if user tries to open or close browser multiple times.

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#818] opened 2019-09-17 08:30 UTC
**Actual Behaviour**
If openBrowser is called multiple times, multiple chromium instances are launched. Taiko retains the references and the CRI connection only to the most recent chromium instance.

If close Browser is called multiple times, Taiko is able to close only the most recent chromium instance. Since, the references to other chromium instances are lost, it fails to close them.
```
TypeError: Cannot read property ‘removeAllListeners’ of null
       at Chrome.reconnect (...../...../....../node_modules/taiko/lib/taiko.js:137:13)
       at Chrome.emit (events.js:198:13)
       at WebSocket._ws.on (...../...../....../node_modules/chrome-remote-interface/lib/chrome.js:233:22)
       at WebSocket.emit (events.js:198:13)
       at WebSocket.emitClose (...../...../....../node_modules/ws/lib/websocket.js:191:10)
       at Socket.socketOnClose (...../...../....../node_modules/ws/lib/websocket.js:850:15)
       at Socket.emit (events.js:198:13)
       at TCP._handle.close (net.js:606:12)
```
**Expected Behaviour**
Taiko should throw an error to user mentioning that openBrowser cannot be called again as there is a chromium instance open(closeBrowser is not yet called).

Taiko should fail with appropriate message, if close browser is called multiple times without calling openBrowser.

**Comment by suganya-sangith** [comment] 2019-10-04 12:21
@nehashri  Will work on it

**Comment by Apoorva-GA** [comment] 2019-10-10 05:54
>Taiko should throw an error to user mentioning that openBrowser cannot be called again as there is a chromium instance open(closeBrowser is not yet called).

[PR](https://github.com/getgauge/taiko/pull/865) address the above point. Fix available in commit d4622518d454a0c2f94e26c2d42e2e9e15d1ef11.

-------------------------------------------------------------------------------
>Taiko should fail with appropriate message, if close browser is called multiple times without calling openBrowser.

This is yet to be fixed

**Comment by Debashis9012** [comment] 2019-10-16 09:12
Calling `openBrowser` api multiple times gives the below error message:
```✘ Error: OpenBrowser cannot be called again as there is a chromium instance open., run `.trace` for more info. ```

Tested version:
`Version: 1.0.3 (Chromium: 76.0.3803.0) d4622518d454a0c2f94e26c2d42e2e9e15d1ef11`

The same behaviour should be implemented for `closeBrowser` api.
So moving it to backlog.

**Comment by suganya-sangith** [comment] 2019-10-18 01:00
> > Taiko should throw an error to user mentioning that openBrowser cannot be called again as there is a chromium instance open(closeBrowser is not yet called).
> 
> [PR](https://github.com/getgauge/taiko/pull/865) address the above point. Fix available in commit [d462251](https://github.com/getgauge/taiko/commit/d4622518d454a0c2f94e26c2d42e2e9e15d1ef11).
> 
> > Taiko should fail with appropriate message, if close browser is called multiple times without calling openBrowser.
> 
> This is yet to be fixed

Totally missed about the closeBrowser, will check it 👍

**Comment by trein-homeroom** [comment] 2019-10-30 23:03
Multi-browser testing is needed for multi-user testing.  It would be ideal if openBrowser returned the ID of the browser session, switchTo supported switching based on ID, and closeBrowser optionally take an ID of which session to switch to after closing the current one.

**Comment by zabil** [comment] 2019-11-05 12:28
The right fix for this is to support profiles and focus on the browser profile when calling `openBrowser`

`openBrowser` must 

* Open a new browser instance when there are no existing instances
* Switch to default profile and maybe display a warning (not an error) when something is open

Also refer https://github.com/getgauge/taiko/issues/921

**Comment by NivedhaSenthil** [comment] 2020-04-03 09:00
Since supporting profiles is closed in favour of incognito contexts.. I believe we just have to warn the user trying to closeBrowser multiple times for this issue

**Comment by zabil** [comment] 2020-04-03 13:51
Yes. Currently I think it is an error. This should be changed to a warning.

**Closed** 2020-04-07 04:06 UTC
Labels: bug

**Comment by wilkerlucio** [comment] 2020-04-25 00:55
I'm still seeing this issue on my pipeline, and I can confirm if I remove the `closeBrowser` it doesn't happen, is this deployed on `1.0.8`?

By the way, I was in `1.0.2` before and didn't have this issue, I was upgrading in the hopes of fixing something else, but then I got to this.

**Comment by zabil** [comment] 2020-04-27 12:09
> I can confirm if I remove the closeBrowser it doesn't happen, is this deployed on 1.0.8?

Do you mean that `closeBrowser` raises an error when it's called multiple times? (which is the original intent of this issue)
