### ISSUE TITLE
Error: Cannot find module 'taiko' his is probably not a problem with npm. There is likely additional logging output above. npm WARN Local package.json exists, but node_modules missing, did you mean to install?

### ISSUE THREAD

**Issue by amolkumar1331** [getgauge/taiko#2325] opened 2021-09-22 05:53 UTC
Getting the below error post running the node script

Error: Cannot find module 'taiko'

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gauge-taiko-template@0.0.1 test:uat:EPL2LL: `gauge run specs/ --tags=EPL2LL --env=uat`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gauge-taiko-template@0.0.1 test:uat:EPL2LL script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by zabil** [comment] 2021-09-22 07:35
This should work after you run an`npm install` before `gauge run` command.
Closing this as it's an install issue. If it still does not work can you share more info with steps and version info to reproduce this error?

**Closed by zabil** 2021-09-22 07:35 UTC

**Comment by amolkumar1331** [comment] 2021-09-23 06:40
I have installed node,Gauge and Taiko.while running the script I am just using the command npm run tagname and post running this command i am getting the below error
Error: Cannot find module 'taiko'

and I have installed the taiko version 1.2.7
![image](https://user-images.githubusercontent.com/53901503/134464246-9d13be24-4be8-46ce-8bc8-6b7f43133b15.png)
![image](https://user-images.githubusercontent.com/53901503/134464355-4e1ae7ed-4779-400d-be8f-23ab29ba361c.png)

**Comment by zabil** [comment] 2021-09-23 08:42
The taiko version you've installed is a global version, while the `gauge run` commands will need a local version of taiko installed. You need to run `npm install` command in the folder `gauge-taiko-template`

**Comment by amolkumar1331** [comment] 2021-09-27 06:39
Hi Zabil,

I am getting the below error post runnig the npm install command in Gauge-taiko template.

![image](https://user-images.githubusercontent.com/53901503/134856798-77512989-c3b9-4dd4-9cd7-2e895eccae11.png)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:397:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\TelstraGlobal\Framework\testing-new\gauge-taiko-tests\node_modules\fibers
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok


I have installed the VS version is 1.60
![image](https://user-images.githubusercontent.com/53901503/134856941-52a86ecc-19f8-4db5-bfc9-1fac87b9c4f8.png)

Could you please let me know what i have to do ?

**Comment by zabil** [comment] 2021-09-27 09:21
Looks like the error is not related to Taiko but about node and it's dependencies. There are a few answers available if you google search for the error for example.

https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c
