### ISSUE TITLE
Should launch chromium seamlessly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#195] opened 2018-10-03 06:24 UTC
**Expected behavior**
Should launch chromium seamlessly 

**Actual behavior**
Getting the following error on CI 
> Observation: Taiko is installed locally on this Windows CI box

https://build.gauge.org/go/tab/build/detail/Taiko/288/specs/1/windows-specs
```
 Error Message: Error: Failed to launch chrome!
    [1003/054248.384:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from C:\go\pipelines\Taiko\js-taiko\node_modules\taiko\.local-chromium\win64-571040\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)

    Stacktrace: 
    Error: Failed to launch chrome!
    [1003/054248.384:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from node_modules\taiko\.local-chromium\win64-571040\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)

        at onClose (node_modules\taiko\lib\browserFetcher.js:190:24)
        at ChildProcess.helper.addEventListener (node_modules\taiko\lib\browserFetcher.js:179:70)
        at ChildProcess.emit (events.js:160:13)

    Error Message: Error: Browser or page not initialized. Call `openBrowser()` before using this API
    Stacktrace: 
    Error: Browser or page not initialized. Call `openBrowser()` before using this API
        at validate (node_modules\taiko\lib\taiko.js:1656:30)
        at module.exports.closeBrowser (node_modules\taiko\lib\taiko.js:108:5)
        at Object.afterScenario (tests\step_implementation.js:20:32)
```
**Steps to replicate**
* Run the specs on CI https://build.gauge.org/go/tab/pipeline/history/Taiko

**Version**
```
commit - 87f2768a479221df595b886e22106b116cf9c681
```

**Comment by BugDiver** [comment] 2018-10-09 06:00
Seems like an issue with chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=873097#c4

**Comment by NivedhaSenthil** [comment] 2018-10-10 05:18
Moving to backlog and wait for chromium to fix the issue. As we don't want to downgrade bundled chromium version.

**Comment by zabil** [comment] 2018-10-31 15:46
Latest comment says the the issue is resolved

**Closed** 2018-11-13 07:53 UTC
Labels: ready for QA
