### ISSUE TITLE
I would like to have a wait until command

### ISSUE THREAD

**Issue by varayal** [getgauge/taiko#396] opened 2019-02-11 19:05 UTC
Sometimes my test failed because of an element that is being covered by another element. This is due to timing.

Is there any command to indicate wait until an element is present to perform the next action?

Example of my tests

**First execution**

` ✔ Clicked element matching text "INICIAR SESIÓN SEGURA"
Error: Element matching text "Depósito bancario" is coverred by other element
    at click (/Users/varaya/Projects/web-automation/front-linio-gauge/node_modules/taiko/lib/taiko.js:448:15)
 ✔ Browser closed`

**Second Execution**

If I run the same test again now the test passed

` ✔ Clicked element matching text "INICIAR SESIÓN SEGURA"
 ✔ Clicked element matching text "Depósito bancario"
 ✔ Clicked element matching text "GUARDAR Y CONTINUAR"`

My point is, I don't want to use "await waitFor(intervalSecs(5));" because the time varies depends on the server response.

I was looking for waitUntil command but I did not find it on the documentation published... Any thoughts?

**Comment by NivedhaSenthil** [comment] 2019-02-12 04:47
Duplicate of https://github.com/getgauge/taiko/issues/125, please add your thoughts there

**Closed by NivedhaSenthil** 2019-02-12 04:47 UTC
Labels: community
