### ISSUE TITLE
Enable basic authentication

### ISSUE THREAD

**Issue by ajoecker** [getgauge/taiko#82] opened 2018-07-30 11:35 UTC
### Expected behavior
When browsing a webpage, that requires basic authentication, I expect to be able to pass taiko the credentials

### Actual behavior
When calling `goto` with a webpage that requires basic authentication, the script holds and does not proceed.

### Versions
```
$ node -v
v8.11.3

taiko
Version: 0.0.9
```

**Comment by zabil** [comment] 2018-07-30 11:41
Add a parameter to the `goto` method that allows passing header values to url for e.g

```
goto('http://example.com', {
    headers: {
        Authorization: `Basic ${encodedCredentials}`
    });
```

**Comment by zabil** [comment] 2018-07-30 14:20
The problem is there are too many header fields
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Standard_request_fields

This will bloat the API and make discovery of the other API's difficult. Also headers maybe repeated across request where it's much easier to declare a variable for re-use

For e.g.
```
var commonHeaders = { headers : ....}
```

This JSON can be merged, overwritten etc.

And visually it's nice to see all the headers fields posted at a glance.

```
goto('http://example.com', {
    headers: {
        Authorization    : `Basic ${encodedCredentials}`,
        From             : 'someone@email.com',
        Proxy-Authorization   : Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
        User-Agent                : 'Firefox'
    });
```

**Comment by NivedhaSenthil** [comment] 2018-08-06 05:08
Fix should be available. Authentication can be done by setting extra headers like below example. 

```
(async ()=>{
    await openBrowser({headless:false});
    await goto("https://postman-echo.com/basic-auth",{headers:{'Authorization':'Basic cG9zdG1hbjpwYXNzd29yZA=='}});
    await closeBrowser();
})();
```

PS: Invalid credentials will not be handled with this, as browser allows to do multiple retries on invalid credentials when set on headers.

**Comment by SanjuSona-19** [comment] 2020-01-30 06:58
I want to keep a login page to be in login even after the chromium is closed. how to achieve this. is there any command is there for keep the cookies not cleared in chromium and to retrieve data from the cookies to avoid multiple login.
help me out to clear this.

**Comment by SanjuSona-19** [comment] 2020-01-30 07:00
The goto is not waiting until the login process is completing. what to do now? @NivedhaSenthil

**Comment by BugDiver** [comment] 2020-01-30 07:09
have you tried using a custom profile directory?

Something like `openBrowser({args:["--user-data-dir" : "/some/profile/path"]})` should preserve browser state in the directory mentioned.

**Closed** 2020-01-30 07:10 UTC

**Comment by SanjuSona-19** [comment] 2020-01-30 08:06
no i didn't used any custom profile. @BugDiver

**Comment by zabil** [comment] 2020-01-30 09:28
@SanjuSona-19 as @BugDiver mentioned please use a custom profile directory to save login states between runs.

The best place to discuss further issues about this is now the support forum for Gauge at https://spectrum.chat/gauge
